bigWigToBedGraph Human_Astrocyte1.meth.bw Human_Astrocyte1.meth.bedgraph
bigWigToBedGraph Human_AS-Fibroblast1.meth.bw Human_AS-Fibroblast1.meth.bedgraph
bigWigToBedGraph Human_PANC1-1.meth.bw Human_PANC1-1.meth.bedgraph
bigWigToBedGraph Human_HeLa1.meth.bw Human_HeLa1.meth.bedgraph
bigWigToBedGraph Human_RPTEC1.meth.bw Human_RPTEC1.meth.bedgraph
bigWigToBedGraph Human_LNCaP1.meth.bw Human_LNCaP1.meth.bedgraph
bigWigToBedGraph Human_NHBE1.meth.bw Human_NHBE1.meth.bedgraph
bigWigToBedGraph Human_AEPiC1.meth.bw Human_AEPiC1.meth.bedgraph
bigWigToBedGraph Human_T47D-DMSO.meth.bw Human_T47D-DMSO.meth.bedgraph
bigWigToBedGraph Human_Testis1.meth.bw Human_Testis1.meth.bedgraph
bigWigToBedGraph Human_IPEpiC1.meth.bw Human_IPEpiC1.meth.bedgraph
bigWigToBedGraph Human_Stomach1.meth.bw Human_Stomach1.meth.bedgraph
bigWigToBedGraph Human_NB4-1.meth.bw Human_NB4-1.meth.bedgraph
bigWigToBedGraph Human_PAEpiC1.meth.bw Human_PAEpiC1.meth.bedgraph
bigWigToBedGraph Human_SAEC1.meth.bw Human_SAEC1.meth.bedgraph
bigWigToBedGraph Human_Fibrobl1.meth.bw Human_Fibrobl1.meth.bedgraph
bigWigToBedGraph Human_MCF10A-Er-Src-TAM.meth.bw Human_MCF10A-Er-Src-TAM.meth.bedgraph
bigWigToBedGraph Human_BLymph4.meth.bw Human_BLymph4.meth.bedgraph
bigWigToBedGraph Human_Astrocyte2.meth.bw Human_Astrocyte2.meth.bedgraph
bigWigToBedGraph Human_RPEpiC1.meth.bw Human_RPEpiC1.meth.bedgraph
bigWigToBedGraph Human_CM1.meth.bw Human_CM1.meth.bedgraph
bigWigToBedGraph Human_LNCaP-Androgen.meth.bw Human_LNCaP-Androgen.meth.bedgraph
bigWigToBedGraph Human_NPCEpiC1.meth.bw Human_NPCEpiC1.meth.bedgraph
bigWigToBedGraph Human_BJ1.meth.bw Human_BJ1.meth.bedgraph
bigWigToBedGraph Human_Pericardium1.meth.bw Human_Pericardium1.meth.bedgraph
bigWigToBedGraph Human_PrEC1.meth.bw Human_PrEC1.meth.bedgraph
bigWigToBedGraph Human_Jurkat1.meth.bw Human_Jurkat1.meth.bedgraph
bigWigToBedGraph Human_MEC1.meth.bw Human_MEC1.meth.bedgraph
bigWigToBedGraph Human_MCF10A-Er-Src-1.meth.bw Human_MCF10A-Er-Src-1.meth.bedgraph
bigWigToBedGraph Human_Skin1.meth.bw Human_Skin1.meth.bedgraph
bigWigToBedGraph Human_Osteobl1.meth.bw Human_Osteobl1.meth.bedgraph
bigWigToBedGraph Human_Placenta1.meth.bw Human_Placenta1.meth.bedgraph
bigWigToBedGraph Human_ECC1-1.meth.bw Human_ECC1-1.meth.bedgraph
bigWigToBedGraph Human_Liver1.meth.bw Human_Liver1.meth.bedgraph
bigWigToBedGraph Human_BLymph3.meth.bw Human_BLymph3.meth.bedgraph
bigWigToBedGraph Human_FT-Fibroblast1.meth.bw Human_FT-Fibroblast1.meth.bedgraph
bigWigToBedGraph Human_Leukocyte1.meth.bw Human_Leukocyte1.meth.bedgraph
bigWigToBedGraph Human_Melano1.meth.bw Human_Melano1.meth.bedgraph
bigWigToBedGraph Human_CMK1.meth.bw Human_CMK1.meth.bedgraph
bigWigToBedGraph Human_ProgFib1.meth.bw Human_ProgFib1.meth.bedgraph
bigWigToBedGraph Human_BLymph1.meth.bw Human_BLymph1.meth.bedgraph
bigWigToBedGraph Human_GT-Fibroblast1.meth.bw Human_GT-Fibroblast1.meth.bedgraph
bigWigToBedGraph Human_Lung1.meth.bw Human_Lung1.meth.bedgraph
bigWigToBedGraph Human_IMR90-1.meth.bw Human_IMR90-1.meth.bedgraph
bigWigToBedGraph Human_SkeletalMuscle1.meth.bw Human_SkeletalMuscle1.meth.bedgraph
bigWigToBedGraph Human_Toe-Fibroblast1.meth.bw Human_Toe-Fibroblast1.meth.bedgraph
bigWigToBedGraph Human_SKNMC1.meth.bw Human_SKNMC1.meth.bedgraph
bigWigToBedGraph Human_Lymphobl1.meth.bw Human_Lymphobl1.meth.bedgraph
bigWigToBedGraph Human_SMM1.meth.bw Human_SMM1.meth.bedgraph
bigWigToBedGraph Human_EEpiC1.meth.bw Human_EEpiC1.meth.bedgraph
bigWigToBedGraph Human_PanIslets1.meth.bw Human_PanIslets1.meth.bedgraph
bigWigToBedGraph Human_RE1.meth.bw Human_RE1.meth.bedgraph
bigWigToBedGraph Human_Hepatocyte1.meth.bw Human_Hepatocyte1.meth.bedgraph
bigWigToBedGraph Human_Breast1.meth.bw Human_Breast1.meth.bedgraph
bigWigToBedGraph Human_PFSK1.meth.bw Human_PFSK1.meth.bedgraph
bigWigToBedGraph Human_NT2-1.meth.bw Human_NT2-1.meth.bedgraph
bigWigToBedGraph Human_RCEpiC1.meth.bw Human_RCEpiC1.meth.bedgraph
bigWigToBedGraph Human_MCF7-1.meth.bw Human_MCF7-1.meth.bedgraph
bigWigToBedGraph Human_AdrenalGland1.meth.bw Human_AdrenalGland1.meth.bedgraph
bigWigToBedGraph Human_LeftVentricle1.meth.bw Human_LeftVentricle1.meth.bedgraph
bigWigToBedGraph Human_CF1.meth.bw Human_CF1.meth.bedgraph
bigWigToBedGraph Human_Myometr1.meth.bw Human_Myometr1.meth.bedgraph
bigWigToBedGraph Human_Lymphobl-XiMat1.meth.bw Human_Lymphobl-XiMat1.meth.bedgraph
bigWigToBedGraph Human_U87-1.meth.bw Human_U87-1.meth.bedgraph
bigWigToBedGraph Human_SKNSH-RA1.meth.bw Human_SKNSH-RA1.meth.bedgraph
bigWigToBedGraph Human_Uterus1.meth.bw Human_Uterus1.meth.bedgraph
bigWigToBedGraph Human_HTB11-1.meth.bw Human_HTB11-1.meth.bedgraph
bigWigToBedGraph Human_SkeletalMuscle2.meth.bw Human_SkeletalMuscle2.meth.bedgraph
bigWigToBedGraph Human_BLymph2.meth.bw Human_BLymph2.meth.bedgraph
bigWigToBedGraph Human_H1-ESC1.meth.bw Human_H1-ESC1.meth.bedgraph
bigWigToBedGraph Human_HCT116-1.meth.bw Human_HCT116-1.meth.bedgraph
bigWigToBedGraph Human_T47D-Estradiol.meth.bw Human_T47D-Estradiol.meth.bedgraph
bigWigToBedGraph Human_EK293-1.meth.bw Human_EK293-1.meth.bedgraph
bigWigToBedGraph Human_K562-1.meth.bw Human_K562-1.meth.bedgraph
bigWigToBedGraph Human_BE2C1.meth.bw Human_BE2C1.meth.bedgraph
bigWigToBedGraph Human_Brain1.meth.bw Human_Brain1.meth.bedgraph
bigWigToBedGraph Human_Pancreas1.meth.bw Human_Pancreas1.meth.bedgraph
bigWigToBedGraph Human_HTR8svn1.meth.bw Human_HTR8svn1.meth.bedgraph
bigWigToBedGraph Human_SMMtube1.meth.bw Human_SMMtube1.meth.bedgraph
bigWigToBedGraph Human_AoSMC1.meth.bw Human_AoSMC1.meth.bedgraph
bigWigToBedGraph Human_AoSMC1.meth.bw Human_AoSMC1.meth.bedgraph
bigWigToBedGraph Human_NHDFneo1.meth.bw Human_NHDFneo1.meth.bedgraph
bigWigToBedGraph Human_HepG2-1.meth.bw Human_HepG2-1.meth.bedgraph
bigWigToBedGraph Human_FL-Fibroblast1.meth.bw Human_FL-Fibroblast1.meth.bedgraph
bigWigToBedGraph Human_Kidney1.meth.bw Human_Kidney1.meth.bedgraph
bigWigToBedGraph Human_SKMC1.meth.bw Human_SKMC1.meth.bedgraph
