wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_Astrocyte1/tracks_hg38/Human_Astrocyte1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_AS-Fibroblast1/tracks_hg38/Human_AS-Fibroblast1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_PANC1-1/tracks_hg38/Human_PANC1-1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_HeLa1/tracks_hg38/Human_HeLa1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_RPTEC1/tracks_hg38/Human_RPTEC1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_LNCaP1/tracks_hg38/Human_LNCaP1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_NHBE1/tracks_hg38/Human_NHBE1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_AEPiC1/tracks_hg38/Human_AEPiC1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_T47D-DMSO/tracks_hg38/Human_T47D-DMSO.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_Testis1/tracks_hg38/Human_Testis1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_IPEpiC1/tracks_hg38/Human_IPEpiC1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_Stomach1/tracks_hg38/Human_Stomach1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_NB4-1/tracks_hg38/Human_NB4-1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_PAEpiC1/tracks_hg38/Human_PAEpiC1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_SAEC1/tracks_hg38/Human_SAEC1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_Fibrobl1/tracks_hg38/Human_Fibrobl1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_MCF10A-Er-Src-TAM/tracks_hg38/Human_MCF10A-Er-Src-TAM.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_BLymph4/tracks_hg38/Human_BLymph4.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_Astrocyte2/tracks_hg38/Human_Astrocyte2.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_RPEpiC1/tracks_hg38/Human_RPEpiC1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_CM1/tracks_hg38/Human_CM1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_LNCaP-Androgen/tracks_hg38/Human_LNCaP-Androgen.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_NPCEpiC1/tracks_hg38/Human_NPCEpiC1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_BJ1/tracks_hg38/Human_BJ1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_Pericardium1/tracks_hg38/Human_Pericardium1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_PrEC1/tracks_hg38/Human_PrEC1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_Jurkat1/tracks_hg38/Human_Jurkat1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_MEC1/tracks_hg38/Human_MEC1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_MCF10A-Er-Src-1/tracks_hg38/Human_MCF10A-Er-Src-1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_Skin1/tracks_hg38/Human_Skin1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_Osteobl1/tracks_hg38/Human_Osteobl1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_Placenta1/tracks_hg38/Human_Placenta1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_ECC1-1/tracks_hg38/Human_ECC1-1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_Liver1/tracks_hg38/Human_Liver1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_BLymph3/tracks_hg38/Human_BLymph3.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_FT-Fibroblast1/tracks_hg38/Human_FT-Fibroblast1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_Leukocyte1/tracks_hg38/Human_Leukocyte1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_Melano1/tracks_hg38/Human_Melano1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_CMK1/tracks_hg38/Human_CMK1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_ProgFib1/tracks_hg38/Human_ProgFib1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_BLymph1/tracks_hg38/Human_BLymph1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_GT-Fibroblast1/tracks_hg38/Human_GT-Fibroblast1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_Lung1/tracks_hg38/Human_Lung1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_IMR90-1/tracks_hg38/Human_IMR90-1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_SkeletalMuscle1/tracks_hg38/Human_SkeletalMuscle1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_Toe-Fibroblast1/tracks_hg38/Human_Toe-Fibroblast1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_SKNMC1/tracks_hg38/Human_SKNMC1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_Lymphobl1/tracks_hg38/Human_Lymphobl1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_SMM1/tracks_hg38/Human_SMM1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_EEpiC1/tracks_hg38/Human_EEpiC1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_PanIslets1/tracks_hg38/Human_PanIslets1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_RE1/tracks_hg38/Human_RE1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_Hepatocyte1/tracks_hg38/Human_Hepatocyte1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_Breast1/tracks_hg38/Human_Breast1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_PFSK1/tracks_hg38/Human_PFSK1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_NT2-1/tracks_hg38/Human_NT2-1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_RCEpiC1/tracks_hg38/Human_RCEpiC1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_MCF7-1/tracks_hg38/Human_MCF7-1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_AdrenalGland1/tracks_hg38/Human_AdrenalGland1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_LeftVentricle1/tracks_hg38/Human_LeftVentricle1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_CF1/tracks_hg38/Human_CF1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_Myometr1/tracks_hg38/Human_Myometr1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_Lymphobl-XiMat1/tracks_hg38/Human_Lymphobl-XiMat1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_U87-1/tracks_hg38/Human_U87-1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_SKNSH-RA1/tracks_hg38/Human_SKNSH-RA1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_Uterus1/tracks_hg38/Human_Uterus1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_HTB11-1/tracks_hg38/Human_HTB11-1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_SkeletalMuscle2/tracks_hg38/Human_SkeletalMuscle2.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_BLymph2/tracks_hg38/Human_BLymph2.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_H1-ESC1/tracks_hg38/Human_H1-ESC1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_HCT116-1/tracks_hg38/Human_HCT116-1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_T47D-Estradiol/tracks_hg38/Human_T47D-Estradiol.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_EK293-1/tracks_hg38/Human_EK293-1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_K562-1/tracks_hg38/Human_K562-1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_BE2C1/tracks_hg38/Human_BE2C1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_Brain1/tracks_hg38/Human_Brain1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_Pancreas1/tracks_hg38/Human_Pancreas1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_HTR8svn1/tracks_hg38/Human_HTR8svn1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_SMMtube1/tracks_hg38/Human_SMMtube1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_AoSMC1/tracks_hg38/Human_AoSMC1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_AoSMC1/tracks_hg38/Human_AoSMC1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_NHDFneo1/tracks_hg38/Human_NHDFneo1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_HepG2-1/tracks_hg38/Human_HepG2-1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_FL-Fibroblast1/tracks_hg38/Human_FL-Fibroblast1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_Kidney1/tracks_hg38/Human_Kidney1.meth.bw
wget http://smithlab.usc.edu/methbase/data/ENCODE-Project-Human-2011/Human_SKMC1/tracks_hg38/Human_SKMC1.meth.bw
